### ISSUE TITLE
Non standard postgres port

### ISSUE THREAD

**Issue by aiyoh79** [ome/omego#118]
Is it possible to specify non-standard postgres port instead of standard 5432?

**Comment by joshmoore** [comment]
@aiyoh79 : you are currently using something like `omego install --dbhost ...` ? If so, unfortunately, no: there is currently no `--dbport` option. You might be able to workaround this with [PGPORT](https://www.postgresql.org/docs/9.3/libpq-envars.html), but it really should be added to the library.

**Comment by aiyoh79** [comment]
@joshmoore , i am currently trying to setup Omero via [Docker](https://hub.docker.com/r/openmicroscopy/omero-server/) and for the database, i am using [Patroni](https://github.com/zalando/patroni) setup. For Patroni, there is HAproxy fronting the database server.

**Comment by joshmoore** [comment]
Hi @aiyoh79. For the omero-server docker image, the configuration is supported. Use:

```
-e CONFIG_omero_db_port=5433 \
```

**Comment by aiyoh79** [comment]
@joshmoore, when i run omero-server Docker, it cannot progress beyond database connection check. The 60-database.sh does not seems to have any reference for CONFIG_omero_db_port. I can add in port number for the script to go to database initialization section and this is where omego come in.

**Comment by joshmoore** [comment]
Ah, @aiyoh79, apologies. I forgot that I had run into the same problem myself! See https://github.com/openmicroscopy/omero-server-docker/pull/20

You're welcome to give that a try. Otherwise, I'll try to refresh my memory on where we are here.

**Comment by aiyoh79** [comment]
@joshmoore, looking at [openmicroscopy/omero-server-docker#20](https://github.com/openmicroscopy/omero-server-docker/pull/20), am i right to say that the omego part for non standard port is still not implemented yet.

**Comment by joshmoore** [comment]
@aiyoh79: that's the point of the testing that I got to yesterday evening, yes. In the mean time, you can use the `redirect` trick using `socat` from https://github.com/openmicroscopy/omero-server-docker/pull/20#issuecomment-370364542 if you need.

**Comment by aiyoh79** [comment]
@joshmoore , ok. For the time being, i will just hardcode this line '-p','5000' to [db.py](https://github.com/ome/omego/blob/2dadbf3c6342b6c995f9e0dceaf3c0b7fab030fb/omego/db.py#L264).

**Comment by manics** [comment]
Closing, this is not related to omego.
