### ISSUE TITLE
specify ice version

### ISSUE THREAD

**Issue by jburel** [ome/omego#84]
In https://github.com/ome/omero-install/pull/94, we now use omego to install the desire build (latest, merge, release)
We will need to be able to specify the version of the server i.e. ice36 build instead of ice35 corresponding to the version of ice installed.

**Comment by manics** [comment]
First commit here: https://github.com/manics/omego/commit/0bf53be7045d6df134fab59e8d979c2692593c68

Still needs tests

**Comment by joshmoore** [comment]
@jburel : next step here?

**Comment by jburel** [comment]
I have deployed ice 3.6 on breaking node, currently an issue on slice2py path
as discussed we won't use omego for the release documentation
this can be done afterwards
