### ISSUE TITLE
Version sourcing

### ISSUE THREAD

**Issue by aleksandra-tarkowska** [ome/omego#95]
incorrect version

```
+ /home/omero/omeroenv/bin/pip install omego==0.4.0
You are using pip version 7.1.0, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting omego==0.4.0
  Downloading omego-0.4.0.tar.gz
  Requested omego==0.4.0 from https://pypi.python.org/packages/a8/11/323d146d44fb1cf85f561213ffe52bc90fd661c0ed072886c64ade4b000c/omego-0.4.0.tar.gz#md5=acebfa3b1588c90aae0c201eb0b02864, but installing version None
Collecting yaclifw>=0.1.1 (from omego==0.4.0)
  Downloading yaclifw-0.1.2.tar.gz
Collecting argparse (from yaclifw>=0.1.1->omego==0.4.0)
  Downloading argparse-1.4.0-py2.py3-none-any.whl
Building wheels for collected packages: omego, yaclifw
  Running setup.py bdist_wheel for omego
  Stored in directory: /home/omero/.cache/pip/wheels/ca/f3/1c/fe442d9e65866cd93074936cf2dd21a245ec27476082b9edb9
  Running setup.py bdist_wheel for yaclifw
  Stored in directory: /home/omero/.cache/pip/wheels/6f/68/84/fe07e9112771e8a3c2daf6540556e1df76e979b161a2b4e71b
Successfully built omego yaclifw
Installing collected packages: argparse, yaclifw, omego
Successfully installed argparse-1.4.0 omego-UNKNOWN yaclifw-0.1.2
```

**Comment by sbesson** [comment]
Retested from a virtualenv

```
[sbesson@ome-c6100-1 ~]$ virtualenv venv
New python executable in venv/bin/python
Installing setuptools, pip...done.
[sbesson@ome-c6100-1 ~]$ source venv/bin/activate
(venv)[sbesson@ome-c6100-1 ~]$ pip install omego==0.6.0
Downloading/unpacking omego==0.6.0
  Downloading omego-0.6.0.tar.gz
  Running setup.py (path:/fc/homes/sbesson/venv/build/omego/setup.py) egg_info for package omego
  Requested omego==0.6.0, but installing version UNKNOWN
Downloading/unpacking yaclifw>=0.1.1 (from omego==0.6.0)
  Downloading yaclifw-0.1.2.tar.gz
  Running setup.py (path:/fc/homes/sbesson/venv/build/yaclifw/setup.py) egg_info for package yaclifw
    Module argparse missing. Install via 'pip install argparse'
Downloading/unpacking argparse (from yaclifw>=0.1.1->omego==0.6.0)
  Downloading argparse-1.4.0-py2.py3-none-any.whl
Installing collected packages: omego, yaclifw, argparse
  Running setup.py install for omego
    Installing omego script to /fc/homes/sbesson/venv/bin
  Running setup.py install for yaclifw
    Module argparse missing. Install via 'pip install argparse'
    Installing yaclifw script to /fc/homes/sbesson/venv/bin
Successfully installed omego yaclifw argparse
Cleaning up...
(venv)[sbesson@ome-c6100-1 ~]$ pip install omego==0.6.0
Downloading/unpacking omego==0.6.0
  Downloading omego-0.6.0.tar.gz
  Running setup.py (path:/fc/homes/sbesson/venv/build/omego/setup.py) egg_info for package omego
Requirement already satisfied (use --upgrade to upgrade): yaclifw>=0.1.1 in ./venv/lib/python2.6/site-packages (from omego==0.6.0)
Requirement already satisfied (use --upgrade to upgrade): argparse in ./venv/lib/python2.6/site-packages (from yaclifw>=0.1.1->omego==0.6.0)
Installing collected packages: omego
  Found existing installation: omego UNKNOWN
    Uninstalling omego:
      Successfully uninstalled omego
  Running setup.py install for omego
    Installing omego script to /fc/homes/sbesson/venv/bin
Successfully installed omego
Cleaning up...
(venv)[sbesson@ome-c6100-1 ~]$
```

The is likely due to the usage of the upstream `yaclifw` for retrieving the version. As `yaclifw` is not installed at this point, the version falls back to the default `UNKNOWN`. A secondary consequence of this issue is that the idempotent tests for [ansible-role-omego](https://github.com/openmicroscopy/ansible-role-omego) are failing. /cc @manics 

My proposal would be to review the strategy used for [sourcing the project version](https://packaging.python.org/single_source_version/) and align with the other Python projects (`omero-marshal`, `ome-files-py`, `omero-figure`). /cc @joshmoore @jburel

**Comment by manics** [comment]
To help anyone unfamiliar with the three mentioned projects:
- `ome-file-py` has a `VERSION` file: https://github.com/ome/ome-files-py/blob/master/VERSION
- `omero-figure` and `omero-marshall` have a `VERSION` variable in `setup.py`:
  - https://github.com/ome/omero-figure/blob/v3.0.0/setup.py#L45
  - https://github.com/openmicroscopy/omero-marshal/blob/v0.5.1/setup.py#L15

**Comment by sbesson** [comment]
Thanks @manics, I think the following table summarizes the strategy used for the Python OME projects currently hosted on [Pypi](http://pypi.python.org/)

 Strategy | Projects
-----------|------------
Tag-based version | [scc](https://github.com/openmicroscopy/snoopycrimecop/) [omego](https://github.com/ome/omego) [yaclifw](https://github.com/openmicroscopy/yaclifw)
Version in `__init__.py` | [omero-mapr](https://github.com/ome/omero-mapr)
Version in `VERSION` | [omero-files-py](https://github.com/ome/ome-files-py)
Version in `setup.py` | [omero-figure](https://github.com/ome/omero-figure) [omero-figure](https://github.com/openmicroscopy/omero-marshal) [omero-webtest](https://github.com/openmicroscopy/omero-webtest) [omero-weberror](https://github.com/openmicroscopy/omero-weberror) [omero-gallery](https://github.com/ome/omero-gallery) [ome-ansible-molecule-dependencies](https://github.com/openmicroscopy/ome-ansible-molecule-dependencies)

**Comment by joshmoore** [comment]
In the case of mapr (see https://github.com/ome/omero-mapr/commit/26363550b2b2f7063cd7e587fdf3b13426b7319a), there's a use of the version at runtime.

**Comment by sbesson** [comment]
Thanks for raising the packaging and the runtime use cases for versions. As mentioned in https://packaging.python.org/single_source_version/, encoding the version in `__init__.py` can have some limitations if third-party packages are imported. Storing the version in an external `VERSION` file should technically allows both `setup.py` and `__init__.py` to read it.

**Comment by jburel** [comment]
for omero-figure it is actually in 3 places: ``settings.py``, ``package.json`` and ``setup.py`` (This is a problem!)
I have started to work on reducing that. Let's discuss that asap

**Comment by sbesson** [comment]
@jburel: makes sense. From a pure technical standpoint, would it be doable to store the version in a single external location (`package.json` instead of `VERSION` for `omero-figure`) and load the file and parse the JSON in `setup.py` and `settings.py or are there other constraints?

**Comment by jburel** [comment]
we cannot use ``package.json`` as a "common" place since other apps e.g. gallery do no have one.
We were previously parsing the content of the ``package.json`` in ``setup.py`` the problem was that the file was not included in the "packaged" files
Adding an external will work, just need to be sure it is included

**Comment by sbesson** [comment]
See https://github.com/MicronOxford/webtagging/pull/60 for a similar issue with `package.json` on webtagging (and the proposed resolution by appending to the `MANIFEST.in`)

**Comment by sbesson** [comment]
Started investigating the migration to a single-source version aligning with the strategy used in the Python web apps repositories - see https://github.com/ome/omero-figure/pull/215.

The main problem for all Python packages depending on `yaclifw` (`scc` and `omego` afaik) is the `Version` command which internally heavily `git tag` and even rewrites the version. If we want to switch our strategy, this probably means working simultaneously `yaclifw 0.2.0` to read the version locally exclusively.
